#include "examsystem.h"

#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QRandomGenerator>
#include <algorithm>
#include <random>

bool ExamSystem::loadFromResource(const QString &path)
{
    m_questions.clear();

    QFile file(path);
    if (!file.open(QIODevice::ReadOnly)) {
        loadFallbackQuestions();
        return false;
    }

    const QByteArray data = file.readAll();
    const QJsonDocument doc = QJsonDocument::fromJson(data);
    if (!doc.isArray()) {
        loadFallbackQuestions();
        return false;
    }

    const QJsonArray array = doc.array();
    for (const QJsonValue &value : array) {
        const QJsonObject obj = value.toObject();
        Question q;
        q.prompt = obj.value(QStringLiteral("prompt")).toString();
        q.answerIndex = obj.value(QStringLiteral("answer")).toInt();
        q.explanation = obj.value(QStringLiteral("explanation")).toString();

        const QJsonArray options = obj.value(QStringLiteral("options")).toArray();
        for (const QJsonValue &opt : options) {
            q.options << opt.toString();
        }

        if (!q.prompt.isEmpty() && q.options.size() >= 2 && q.answerIndex >= 0 && q.answerIndex < q.options.size()) {
            m_questions.push_back(q);
        }
    }

    if (m_questions.isEmpty()) {
        loadFallbackQuestions();
        return false;
    }

    return true;
}

QVector<Question> ExamSystem::randomQuestions(int count) const
{
    QVector<Question> result = m_questions;
    std::mt19937 engine(QRandomGenerator::global()->generate());
    std::shuffle(result.begin(), result.end(), engine);

    if (result.size() > count) {
        result.resize(count);
    }
    return result;
}

int ExamSystem::questionCount() const
{
    return m_questions.size();
}

void ExamSystem::loadFallbackQuestions()
{
    m_questions = {
        // 2015年
        {QStringLiteral("以下说法错误的是（）"),
         {QStringLiteral("不能使用抽象类来定义对象"), QStringLiteral("基类的对象不必经过类型转换就可以赋值给派生类的变量"), QStringLiteral("抽象类至少含有一个纯虚函数"), QStringLiteral("对象的成员变量可以是其他类的对象")},
         1,
         QStringLiteral("基类对象不能直接赋值给派生类变量，需要类型转换。")},
        {QStringLiteral("以下说法错误的是（）"),
         {QStringLiteral("类的静态成员要在类外部进行初始化"), QStringLiteral("不需要创建类的对象，就可以访问类的静态成员"), QStringLiteral("类的析构函数中，不允许访问静态成员"), QStringLiteral("静态成员函数内部不可以使用 this 指针")},
         2,
         QStringLiteral("析构函数中可以访问静态成员。")},
        {QStringLiteral("以下说法错误的是（）"),
         {QStringLiteral("在 list 型的容器中，可以同时存储多个相同的元素"), QStringLiteral("向 vector 型容器添加新对象时，需要比较对象的大小"), QStringLiteral("将一个对象放入 STL 中的容器里时，实际上被放入的是该对象的一个拷贝"), QStringLiteral("map 容器支持下标运算符[]")},
         1,
         QStringLiteral("vector添加对象不需要比较大小。")},
        {QStringLiteral("以下 STL 容器中，其元素在容器中的位置与元素的值没有关系的是（）"),
         {QStringLiteral("set"), QStringLiteral("multimap"), QStringLiteral("priority_queue"), QStringLiteral("queue")},
         3,
         QStringLiteral("queue是先进先出，位置与值无关。")},
        {QStringLiteral("A 是一个类，下面的一段程序调用了几次类 A 的构造函数? class A { public: A(int n = 0) { } }; void func(A a) { } int main() { A * a1[3]; A a2[2]; a2[0] = 4; func(a2[0]); return 0; }"),
         {QStringLiteral("2"), QStringLiteral("3"), QStringLiteral("4"), QStringLiteral("5")},
         2,
         QStringLiteral("a2[0]=4 调用一次构造，func传参调用一次拷贝构造，a2数组两个对象各一次构造，共4次。")},
        {QStringLiteral("以下关于静态成员的说法，哪个是正确的？"),
         {QStringLiteral("静态成员函数内部可以调用同类的非静态成员函数"), QStringLiteral("构造函数也可以是静态的"), QStringLiteral("不能通过\"对象名.成员函数名\"的办法调用静态成员函数"), QStringLiteral("静态成员函数不能是虚函数")},
         3,
         QStringLiteral("静态成员函数不能是虚函数。")},
        {QStringLiteral("以下说法哪个是正确的?"),
         {QStringLiteral("双向迭代器可以和整数相加"), QStringLiteral("两个双向迭代器可以相减"), QStringLiteral("两个双向迭代器可以比较大小"), QStringLiteral("list 上面的迭代器不能比较大小")},
         3,
         QStringLiteral("list的迭代器是双向迭代器，不支持比较大小。")},
        {QStringLiteral("下面哪个说法是正确的？"),
         {QStringLiteral("派生类的成员函数内部可以直接访问基类的全部成员"), QStringLiteral("不能不经过强制类型转换就把派生类对象赋值给基类对象"), QStringLiteral("不能不经过强制类型转换就把基类对象赋值给派生类对象"), QStringLiteral("如果基类没有无参构造函数，则写派生类时一定要自己写构造函数")},
         2,
         QStringLiteral("基类对象不能直接赋值给派生类对象，需要强制转换。")},
        {QStringLiteral("以下 STL 中的函数模板哪个可以作用于 set"),
         {QStringLiteral("sort"), QStringLiteral("random_shuffle"), QStringLiteral("find"), QStringLiteral("都不行")},
         2,
         QStringLiteral("find算法可以用于set，因为它只读。")},
        {QStringLiteral("以下说法哪个正确"),
         {QStringLiteral("抽象类不可以有成员变量"), QStringLiteral("抽象类的派生类也可能是抽象类"), QStringLiteral("常量成员函数不能作用于非常量对象"), QStringLiteral("抽象类的成员函数都是纯虚函数")},
         1,
         QStringLiteral("抽象类的派生类如果不实现所有纯虚函数，则仍是抽象类。")},
        {QStringLiteral("下面说法哪个是不对的（）"),
         {QStringLiteral("基类的成员函数可以访问基类的 protected 成员"), QStringLiteral("基类的友元函数可以访问基类的 protected 成员"), QStringLiteral("派生类的成员函数可以访问基类的 protected 成员"), QStringLiteral("若 a 是在派生类的成员函数中定义的局部基类对象，则该成员函数可以直接访问 a 的保护成员")},
         3,
         QStringLiteral("派生类的成员函数不能直接访问基类对象的protected成员，只能访问自己的基类部分。")},
        {QStringLiteral("在程序中，希望定义输出文件流 ofstream 来完成以二进制格式输出到文件 output.txt 尾部，保留 output.txt 的现有数据的工作。应当采用的最正确的打开文件的方式是："),
         {QStringLiteral("ofstream outFile(\"output.txt\",ios::out);"), QStringLiteral("ofstream outFile(\"output.txt\",ios::app);"), QStringLiteral("ofstream outFile(\"output.txt\",ios::out|ios::binary);"), QStringLiteral("ofstream outFile(\"output.txt\",ios::app|ios::binary);")},
         3,
         QStringLiteral("app模式追加，binary二进制。")},
        {QStringLiteral("下列哪类容器提供了排序成员函数 sort"),
         {QStringLiteral("List"), QStringLiteral("Vector"), QStringLiteral("Set"), QStringLiteral("Map")},
         0,
         QStringLiteral("list有自己的sort成员函数。")},
        {QStringLiteral("算法模板 count 不可用于下列哪类容器的元素统计"),
         {QStringLiteral("deque"), QStringLiteral("map"), QStringLiteral("set"), QStringLiteral("priority_queue")},
         3,
         QStringLiteral("priority_queue不支持迭代器，不能用count。")},
        {QStringLiteral("关于析构函数，正确的说法是"),
         {QStringLiteral("析构函数可以是虚函数"), QStringLiteral("一个类可以定义多个析构函数"), QStringLiteral("析构函数可以有参数、也可以没有参数"), QStringLiteral("析构函数可以是 static 成员")},
         0,
         QStringLiteral("析构函数可以是虚函数，用于多态删除。")},
        {QStringLiteral("关于构造函数，错误的说法是"),
         {QStringLiteral("每个类的构造函数的名称是固定的"), QStringLiteral("每个类都有无参数的构造函数"), QStringLiteral("构造函数可以是类的 private 成员"), QStringLiteral("构造函数中不可以访问类的纯 virtual 函数")},
         1,
         QStringLiteral("如果用户定义了构造函数，编译器不再生成默认无参构造函数。")},
        {QStringLiteral("下列哪个运算符的运算符重载函数可以是类的友员函数"),
         {QStringLiteral("下标运算符\"[]\""), QStringLiteral("函数调用运算符\"()\""), QStringLiteral("赋值运算符\"=\""), QStringLiteral("流输入运算符\"<<\"")},
         3,
         QStringLiteral("流运算符通常重载为友元函数。")},
        {QStringLiteral("下面哪个说法是对的？ 构造函数的调用顺序是先基类后派生类 构造函数的调用顺序是先派生类后基类 析构函数的调用顺序是先基类后派生类 析构函数的调用顺序是先派生类后基类"),
         {QStringLiteral("2,4"), QStringLiteral("1,3"), QStringLiteral("1,4"), QStringLiteral("2,3")},
         2,
         QStringLiteral("构造函数先基类后派生类，析构函数先派生类后基类。")},
        {QStringLiteral("关于静态成员函数，哪一个说法是对的？ 它可以访问非静态成员 它可以访问其他静态成员函数 它可以访问全局数据和函数 它可以访问 this 指针"),
         {QStringLiteral("只有 1"), QStringLiteral("只有 2"), QStringLiteral("只有 2, 3, 4"), QStringLiteral("只有 2 , 3")},
         3,
         QStringLiteral("静态成员函数只能访问静态成员和全局数据，没有this指针。")},
        {QStringLiteral("以下关于多态的说法那个不正确?"),
         {QStringLiteral("在成员函数中调用虚函数，是多态"), QStringLiteral("通过\"基类对象名.函数名\"的方式调用虚函数，不是多态"), QStringLiteral("多态的函数调用语句中，函数一定是虚函数"), QStringLiteral("通过\"基类引用名.函数名\"的方式调用虚函数，是多态")},
         0,
         QStringLiteral("在成员函数中调用虚函数，如果通过对象调用则静态绑定，不一定多态。")},

        // 2016年
        {QStringLiteral("在类的成员函数中，可直接访问下列哪类变量"),
         {QStringLiteral("父类的 private 成员"), QStringLiteral("同类其他对象的 private 成员"), QStringLiteral("父类对象的 private 成员"), QStringLiteral("父类对象的 protected 成员")},
         1,
         QStringLiteral("同类对象可以访问彼此的私有成员。")},
        {QStringLiteral("STL 算法模板 SORT 可用于下列哪类容器"),
         {QStringLiteral("STACK"), QStringLiteral("MAP"), QStringLiteral("LIST"), QStringLiteral("DEQUE")},
         3,
         QStringLiteral("deque支持随机访问迭代器，可用sort。")},
        {QStringLiteral("下列哪个函数的返回值类型可以为 void："),
         {QStringLiteral("类的构造函数"), QStringLiteral("类的强制类型转换函数"), QStringLiteral("类的析构函数"), QStringLiteral("类的静态成员函数")},
         3,
         QStringLiteral("静态成员函数可以返回void。")},
        {QStringLiteral("以下说法错误的是（）"),
         {QStringLiteral("一个类的静态成员变量一共就一份，为该类所有对象共享"), QStringLiteral("如果不经转换，则不能把非常量指针赋值给常量指针，也不能把常量指针赋值给非常量指针"), QStringLiteral("如果 A 是 B 的友元类,那么 A 的成员函数可以访问 B 的私有成员"), QStringLiteral("友元类之间的关系既不能传递也不能继承")},
         1,
         QStringLiteral("可以把非常量指针赋值给常量指针，反向不行。")},
        {QStringLiteral("下列关于运算符重载的描述中，正确的是（）"),
         {QStringLiteral("运算符重载为成员函数时，若参数表中无参数，重载的是一元(单目）运算符"), QStringLiteral("一元(单目）运算符只能作为成员函数重载"), QStringLiteral("运算符重载可以改变运算符的优先级"), QStringLiteral("重载自增运算符时，前置形式比后置形式多了一个 int 类型的参数")},
         0,
         QStringLiteral("无参数的一元运算符重载正确。")},
        {QStringLiteral("以下关于构造函数的说法不正确的是（）"),
         {QStringLiteral("构造函数不可以是 private 类型"), QStringLiteral("对 const 成员、引用类型成员以及没有默认构造函数的成员对象，必须通过初始化列表进行初始化"), QStringLiteral("构造函数可以被重载"), QStringLiteral("除复制构造函数以外，单个形参的构造函数定义了从形参类型到该类类型的一个隐式转换")},
         0,
         QStringLiteral("构造函数可以是private，如单例模式。")},
        {QStringLiteral("以下关于静态成员的说法正确的是（）"),
         {QStringLiteral("静态成员函数中可以使用 this 指针"), QStringLiteral("非静态成员函数中不可以调用静态成员函数"), QStringLiteral("静态成员变量不可以定义为 const 类型"), QStringLiteral("静态成员变量可以在非静态成员函数中访问")},
         3,
         QStringLiteral("非静态成员函数可以访问静态成员变量。")},
        {QStringLiteral("以下关于容器迭代器操作，合法的是（）"),
         {QStringLiteral("list<int> l(10); list<int>::iterator it = l.begin()+2;"), QStringLiteral("queue<int> q; sort(q.begin(), q.end());"), QStringLiteral("vector<int> v(5); if (v.begin() < v.end()){cout << \"Yes!\" << endl;}"), QStringLiteral("set<int> s; int set_size = s.end()-s.begin();")},
         2,
         QStringLiteral("vector迭代器支持比较大小。")},
        {QStringLiteral("任意一个类，析构函数的个数最多是（）"),
         {QStringLiteral("不限个数"), QStringLiteral("1"), QStringLiteral("2"), QStringLiteral("3")},
         1,
         QStringLiteral("每个类只有一个析构函数。")},
        {QStringLiteral("下列关于 this 指针的说法，哪个是正确的："),
         {QStringLiteral("this 指针一定指向常量型数据"), QStringLiteral("this 指向的数据不可更改"), QStringLiteral("静态成员函数中也可以使用 this 指针"), QStringLiteral("this 指针本身可直接作为成员函数的返回值")},
         3,
         QStringLiteral("this指针可以作为返回值返回。")},
        {QStringLiteral("下列语句中，将函数 int sum(int x, int y)正确重载的是（）"),
         {QStringLiteral("float sum(int x, int y);"), QStringLiteral("int sum(int a, int b);"), QStringLiteral("float sum(float x, float y);"), QStringLiteral("double sum(int y, int x);")},
         2,
         QStringLiteral("参数类型不同构成重载。")},
        {QStringLiteral("下列的各类函数中，哪个不是类的成员函数："),
         {QStringLiteral("构造函数"), QStringLiteral("析构函数"), QStringLiteral("友元函数"), QStringLiteral("复制构造函数")},
         2,
         QStringLiteral("友元函数不是类的成员函数。")},
        {QStringLiteral("下面对模版的声明，正确的是（）"),
         {QStringLiteral("template < T >"), QStringLiteral("template < class T1, T2 >"), QStringLiteral("template < class T1, class T2 >"), QStringLiteral("template < class T1; class T2 >")},
         2,
         QStringLiteral("多个模板参数需用逗号分隔，每个参数前加class或typename。")},
        {QStringLiteral("下列关于引用的说法，错误的是（）"),
         {QStringLiteral("声明引用时，必须同时对其进行初始化"), QStringLiteral("引用只能引用变量"), QStringLiteral("引用不是变量，因此本身不占存储单元"), QStringLiteral("可以通过常引用去修改其引用的内容")},
         3,
         QStringLiteral("常引用不能修改引用的内容。")},
        {QStringLiteral("哪种情况下，一定不会调用类 A 的复制构造函数"),
         {QStringLiteral("函数返回时，函数的返回值是类 A 的对象"), QStringLiteral("调用函数时，函数的某个参数是类 A 的对象"), QStringLiteral("将类 A 的一个对象赋值给类 A 的另一个对象"), QStringLiteral("用类 A 的一个对象去初始化的类 A 的另一个对象")},
         2,
         QStringLiteral("赋值操作调用赋值运算符，不是拷贝构造。")},
        {QStringLiteral("若基类和派生类均定义了同名的虚函数，则以下情况不可能发生的是（）"),
         {QStringLiteral("使用派生类指针调用该虚函数，实际调用了在基类中定义的虚函数"), QStringLiteral("使用派生类指针调用该虚函数，实际调用了在派生类中定义的虚函数"), QStringLiteral("使用基类指针调用该虚函数，实际调用了在基类中定义的虚函数"), QStringLiteral("使用基类指针调用该虚函数，实际调用了在派生类中定义的虚函数")},
         0,
         QStringLiteral("派生类指针调用虚函数总是调用派生类的版本（如果重写了）。")},
        {QStringLiteral("下列说法错误的是（）"),
         {QStringLiteral("抽象类既可以派生出抽象类，也可以派生出非抽象类"), QStringLiteral("纯虚函数没有函数体"), QStringLiteral("凡是包含虚函数的类都是抽象类"), QStringLiteral("抽象类的构造函数或析构函数内部不能调用自己的纯虚函数")},
         2,
         QStringLiteral("包含虚函数不一定抽象，抽象类必须有纯虚函数。")},
        {QStringLiteral("下列关于函数模板和类模板的说法，错误的是（）"),
         {QStringLiteral("模板中可以有不止一个类型参数"), QStringLiteral("函数模板不可以重载"), QStringLiteral("同一个类模板可能生成不同的类"), QStringLiteral("类模板的成员函数也可以是函数模板")},
         1,
         QStringLiteral("函数模板可以重载。")},
        {QStringLiteral("关于以下函数，有几种可以访问 protected 属性的成员？ 1）类的成员函数 2）类的友员函数 3）派生类的成员函数"),
         {QStringLiteral("0"), QStringLiteral("1"), QStringLiteral("2"), QStringLiteral("3")},
         3,
         QStringLiteral("三种都可以访问protected。")},
        {QStringLiteral("对于有 n 个元素的以下容器，大多数情况下，哪种操作速度最快？"),
         {QStringLiteral("在 deque 头部添加一个元素"), QStringLiteral("在 set 中查找元素"), QStringLiteral("在 vector 头部添加一个元素"), QStringLiteral("在 map 中删除元素")},
         0,
         QStringLiteral("deque头部添加是O(1)。")},

        // 2017年
        {QStringLiteral("关于复制构造函数，下列说法正确的是"),
         {QStringLiteral("系统不会生成缺省复制构造函数，因此必须自己实现"), QStringLiteral("复制构造函数是形如 X::X(X)的函数"), QStringLiteral("Myclass c1, c2; c1.n = 1; c2 = c1;第三句将会调用复制构造函数"), QStringLiteral("调用函数 A Func(){A a(4); return a;}时，将会调用 A 的复制构造函数")},
         3,
         QStringLiteral("函数返回对象时调用拷贝构造。")},
        {QStringLiteral("关于虚函数，下列说法不正确的是"),
         {QStringLiteral("不允许以虚函数作为构造函数"), QStringLiteral("没有虚函数便无法实现多态"), QStringLiteral("一般来讲，如果一个类中定义了虚函数，则不可将析构函数也定义为虚函数"), QStringLiteral("不能用抽象类定义对象")},
         2,
         QStringLiteral("定义了虚函数的类通常应将析构函数设为虚函数。")},
        {QStringLiteral("下列类模板不支持迭代器的是"),
         {QStringLiteral("stack"), QStringLiteral("vector"), QStringLiteral("list"), QStringLiteral("set")},
         0,
         QStringLiteral("stack是容器适配器，不支持迭代器。")},
        {QStringLiteral("关于 this 指针，以下说法不正确的是"),
         {QStringLiteral("static 成员函数内部不可以使用 this 指针"), QStringLiteral("在构造函数内部可以使用 this 指针"), QStringLiteral("在析构函数内部可以使用 this 指针"), QStringLiteral("const 成员函数内部不可以使用 this 指针")},
         3,
         QStringLiteral("const成员函数中可以使用this指针，但指向的是const对象。")},
        {QStringLiteral("将一个对象放入 STL 中的容器里时，以下说法正确的是"),
         {QStringLiteral("实际上被放入的是该对象的指针"), QStringLiteral("实际上被放入的是该对象的一个拷贝（副本）"), QStringLiteral("实际上被放入的是该对象的引用"), QStringLiteral("实际上被放入的就是该对象自身")},
         1,
         QStringLiteral("容器存储的是对象的副本。")},
        {QStringLiteral("关于顺序容器迭代器的操作，不正确的是"),
         {QStringLiteral("vector<int>::iterator iter1, iter2; iter1<iter2;"), QStringLiteral("list<int>::iterator iter1, iter2; iter1<iter2;"), QStringLiteral("vector<int>::iterator iter1; iter1-=3;"), QStringLiteral("deque<int>::iterator iter1; iter1+=5;")},
         1,
         QStringLiteral("list迭代器不支持比较大小。")},
        {QStringLiteral("map 的每个元素包括 KEY(first)和 VALUE(second)。关于 map 容器，下列哪种说法错误"),
         {QStringLiteral("map 支持下标运算符"), QStringLiteral("map 的不同元素可以有相同的 VALUE"), QStringLiteral("map 支持 STL 的 sort 算法"), QStringLiteral("map 支持双向迭代器")},
         2,
         QStringLiteral("map本身有序，不需要sort算法。")},
        {QStringLiteral("下列哪个运算符可以被重载"),
         {QStringLiteral("->"), QStringLiteral("?:"), QStringLiteral("."), QStringLiteral("::")},
         0,
         QStringLiteral("->运算符可以重载。")},
        {QStringLiteral("关于类的 static 成员函数，下列哪个说法正确"),
         {QStringLiteral("static 成员函数中，可以访问当前类的 virtual 成员函数"), QStringLiteral("static 成员函数中，可以访问父类的 private 成员函数"), QStringLiteral("static 成员函数中，不允许调用当前类的非 const 成员函数"), QStringLiteral("static 成员函数中，不允许使用 this 指针")},
         3,
         QStringLiteral("static成员函数没有this指针。")},
        {QStringLiteral("下列说法错误的是"),
         {QStringLiteral("可以在一个类的友元函数中使用 this 指针"), QStringLiteral("每个类只有一个析构函数"), QStringLiteral("抽象类至少包含一个纯虚函数"), QStringLiteral("构造函数不可以是 virtual 函数")},
         0,
         QStringLiteral("友元函数没有this指针。")},
        {QStringLiteral("下列说法正确的是"),
         {QStringLiteral("每个类至少有两个构造函数"), QStringLiteral("构造函数的返回值必须是 void 类型的"), QStringLiteral("有可能通过基类的指针调用派生类的 virtual 函数"), QStringLiteral("C++语法不允许派生类的成员变量和基类的成员变量同名")},
         2,
         QStringLiteral("多态时基类指针可调用派生类虚函数。")},
        {QStringLiteral("下列关于运算符重载的描述中，正确的是:"),
         {QStringLiteral("运算符只能被重载一次"), QStringLiteral("流插入运算符\"<<\"可以是类的友元函数"), QStringLiteral("所有的运算符可以被重载为普通函数，也可以重载为成员函数"), QStringLiteral("运算符重载可以改变运算符的优先级")},
         1,
         QStringLiteral("流运算符通常重载为友元函数。")},
        {QStringLiteral("关于继承和派生的描述中，下列说法错误的是:"),
         {QStringLiteral("派生类的成员函数中，不能访问基类的 private 成员"), QStringLiteral("在派生类的析构函数执行之前，会先调用基类的析构函数"), QStringLiteral("派生类对象的地址可以赋值给基类指针"), QStringLiteral("派生类可以有和基类同名同参数的成员函数")},
         1,
         QStringLiteral("析构顺序：先派生类析构，再基类析构。")},
        {QStringLiteral("以下哪种使用 std::sort 算法的方式是不合法的："),
         {QStringLiteral("vector<int> a; ...; sort(a.begin(), a.end());"), QStringLiteral("bool b[99]; ...; sort(b, b + 99);"), QStringLiteral("string c = \"2333\"; ...; sort(c.begin(), c.end());"), QStringLiteral("list<int> d; ...; sort(d.begin(), d.end());")},
         3,
         QStringLiteral("list迭代器不是随机访问，不能用sort算法。")},
        {QStringLiteral("类 A 重载的运算符声明是 int operator<(A &other) const，那么以下说法中正确的是"),
         {QStringLiteral("小于号左侧的 A 对象不可以是 const 的"), QStringLiteral("小于号右侧的 A 对象不可以是 const 的"), QStringLiteral("这个写法是错误的，因为小于号的返回类型必须是 bool"), QStringLiteral("使用小于号的时候，other 参数处，传进来的对象实际上会被复制一次")},
         1,
         QStringLiteral("右侧参数是非常量引用，不能传const对象。")},
        {QStringLiteral("系统在调用重载函数时，往往根据一些条件确定哪个重载函数被调用，在下列选项中，不能作为依据的是"),
         {QStringLiteral("参数个数"), QStringLiteral("参数的类型"), QStringLiteral("函数的返回值的类型"), QStringLiteral("函数名称")},
         2,
         QStringLiteral("返回值类型不能区分重载。")},
        {QStringLiteral("关于构造函数，下列选项错误的是"),
         {QStringLiteral("构造函数可以是虚函数"), QStringLiteral("构造函数的参数可以有缺省值"), QStringLiteral("定义了构造函数，则编译器不生成默认的无参数的构造函数"), QStringLiteral("构造函数不能继承")},
         0,
         QStringLiteral("构造函数不能是虚函数。")},
        {QStringLiteral("以下顺序容器不支持随机访问迭代器的是"),
         {QStringLiteral("vector"), QStringLiteral("deque"), QStringLiteral("list"), QStringLiteral("以上容器都支持")},
         2,
         QStringLiteral("list是双向迭代器，不支持随机访问。")},
        {QStringLiteral("以下 STL 中的函数模板哪个可以作用于 set"),
         {QStringLiteral("sort"), QStringLiteral("random_shuffle"), QStringLiteral("find"), QStringLiteral("都不行")},
         2,
         QStringLiteral("find算法可用于set。")},
        {QStringLiteral("以下关于多态的说法哪个不正确"),
         {QStringLiteral("在成员函数中调用虚函数，是多态"), QStringLiteral("通过\"基类对象名.函数名\"的方式调用虚函数，不是多态"), QStringLiteral("多态的函数调用语句中，函数一定是虚函数"), QStringLiteral("通过\"基类引用名.函数名\"的方式调用虚函数，是多态")},
         0,
         QStringLiteral("成员函数中调用虚函数可能是静态绑定。")},

        // 2018年
        {QStringLiteral("以下说法正确的是:"),
         {QStringLiteral("一旦某个类的成员函数被声明为虚函数，则在该类的所有派生类中和它同名同参数表的成员函数都是虚函数"), QStringLiteral("只要基类有无参构造函数，则派生类的构造函数就可以不带初始化列表"), QStringLiteral("存在从基类对象向派生类对象的隐式类型转换（自动类型转换）"), QStringLiteral("对虚函数的调用，在编译时就可确定调用哪个类的虚函数")},
         0,
         QStringLiteral("虚函数特性会沿继承链传递。")},
        {QStringLiteral("在以下哪种情形，复制构造函数会被调用。"),
         {QStringLiteral("当一个对象采用引用方式，作为参数传递给一个函数"), QStringLiteral("当一个函数返回一个对象"), QStringLiteral("当一个对象赋值给另一个对象"), QStringLiteral("以上答案都不对")},
         1,
         QStringLiteral("函数返回对象时调用拷贝构造。")},
        {QStringLiteral("下列关于引用的说法，错误的是"),
         {QStringLiteral("声明引用时，必须同时对其进行初始化"), QStringLiteral("引用一旦初始化后就不能再令其引用其它变量"), QStringLiteral("不可以用常量来初始化非常量引用"), QStringLiteral("常引用所引用的变量是不可修改的")},
         3,
         QStringLiteral("常引用不能通过引用修改变量，但变量本身可能被其他方式修改。")},
        {QStringLiteral("以下 STL 中的函数模板哪个可以作用于 vector"),
         {QStringLiteral("lower_bound"), QStringLiteral("random_shuffle"), QStringLiteral("unique"), QStringLiteral("都可以")},
         3,
         QStringLiteral("vector支持这些算法。")},
        {QStringLiteral("下列 STL 模板中，不支持随机访问迭代器的是"),
         {QStringLiteral("queue"), QStringLiteral("vector"), QStringLiteral("deque"), QStringLiteral("string")},
         0,
         QStringLiteral("queue是适配器，没有迭代器。")},
        {QStringLiteral("关于模板，以下说法正确的是？"),
         {QStringLiteral("模板形参只能是类型形参"), QStringLiteral("类模板可以重载"), QStringLiteral("函数模板可以重载"), QStringLiteral("使用同一个类模板实例化出来的不同类的对象可以直接互相赋值")},
         2,
         QStringLiteral("函数模板可以重载。")},
        {QStringLiteral("关于容器，以下说法不正确的是？"),
         {QStringLiteral("map 容器可以显式定义 Key 的排序方式"), QStringLiteral("顺序容器中，在中间插入元素时，list 容器的插入成本最低"), QStringLiteral("顺序容器都可以使用 STL algorithm 里的 sort 函数"), QStringLiteral("vector 容器中的元素要求存放在连续的内存中")},
         2,
         QStringLiteral("list不能使用sort算法，有自己的sort成员。")},
        {QStringLiteral("关于容器迭代器，以下说法正确的是？"),
         {QStringLiteral("关联容器迭代器不支持++操作"), QStringLiteral("顺序容器迭代器都支持 < 操作"), QStringLiteral("容器适配器不支持迭代器操作"), QStringLiteral("对于 list 容器的 insert 操作，insert(iter, element)会在 iter 指向的位置后面插入元素 element")},
         2,
         QStringLiteral("适配器如stack/queue没有迭代器。")},
        {QStringLiteral("关于运算符重载，下列说法错误的是"),
         {QStringLiteral("C++允许用户自定义新的运算符进行重载"), QStringLiteral("当*作为单目运算符时，可以进行重载"), QStringLiteral("重载运算符函数不能有默认参数"), QStringLiteral("重载()运算符时，参数个数可以为任意多个")},
         0,
         QStringLiteral("不能自定义新的运算符。")},
        {QStringLiteral("下列说法中正确的是"),
         {QStringLiteral("可以用参数初始化表对静态数据成员初始化"), QStringLiteral("静态数据成员初始化语句的一般形式为 static 类名：：静态数据成员名=初值"), QStringLiteral("在类外可以通过对象名引用 public 静态数据成员，也可以通过类名引用"), QStringLiteral("静态数据成员不能在类体外进行初始化")},
         2,
         QStringLiteral("静态成员可通过对象或类名访问。")},
        {QStringLiteral("如果一个函数是类 A 的友元函数，下列哪一项是错误的？"),
         {QStringLiteral("该函数只能由类 A 本身声明为友元"), QStringLiteral("该友元函数不是类 A 的成员"), QStringLiteral("该友元函数是类 A 的成员"), QStringLiteral("该友元函数可以访问类 A 的私有的成员")},
         2,
         QStringLiteral("友元函数不是类的成员。")},
        {QStringLiteral("在 C++中，const 限定符可以应用于 1）类的成员函数 2）函数参数 3）静态成 员变量 4）引用"),
         {QStringLiteral("1,2,3。"), QStringLiteral("1,2,4"), QStringLiteral("所有"), QStringLiteral("1,3,4")},
         2,
         QStringLiteral("const可用于所有这些。")},
        {QStringLiteral("关于构造函数，以下说法正确的是："),
         {QStringLiteral("只有一个参数的构造函数是类型转换构造函数。"), QStringLiteral("构造函数不可以被重载。"), QStringLiteral("构造函数可以是私有的。"), QStringLiteral("构造函数可以是虚函数。")},
         2,
         QStringLiteral("构造函数可以是私有的，如单例模式。")},
        {QStringLiteral("以下说法不正确的是："),
         {QStringLiteral("在公有派生的情况下，派生类对象的地址可以直接赋值给基类指针。"), QStringLiteral("在公有派生的情况下，派生类对象可以直接赋值给基类对象。"), QStringLiteral("类的成员函数可以访问其他同类对象的 private 成员。"), QStringLiteral("类的成员函数可以访问其他基类对象的 protected 成员。")},
         3,
         QStringLiteral("不能访问其他基类对象的protected成员。")},
        {QStringLiteral("template < class T, int size > class CArray { static int count; ... }; 其中没有用户自定义的构造函数。由该类模版实例化的两个模版类 CArray<int,40> 和 CArray<int,50>，并且有两个对象： CArray<int,40> c40; CArray<int,50> c50; 以下各个说法正确的个数是： i.CArray<int,40>的对象直接可以用 CArray<int,50>的对象赋值 ii.c40 修改静态变量 count 会改变 c50 中的静态变量 count iii.指针 CArray<int,40>* p 可以直接指向 CArray<int,50> 的对象"),
         {QStringLiteral("0"), QStringLiteral("1"), QStringLiteral("2"), QStringLiteral("3")},
         0,
         QStringLiteral("不同模板实例是不同类型，互不相关。")},
        {QStringLiteral("以下说法正确的个数是： i. ostream 类有公有的无参构造函数，可以用于定义 ostream 类的对象 ii. ostream 类有公有的复制构造函数，可以用于复制 ostream 类的对象 iii. while(cin>>n>>m) 这个语句可以一直输入直到结束，是因为用户重载了流输入运算符>>并且让它在输入出错的时候返回 0，正确的时候返回 1"),
         {QStringLiteral("0"), QStringLiteral("1"), QStringLiteral("2"), QStringLiteral("3")},
         0,
         QStringLiteral("所有说法都错误。")},
        {QStringLiteral("以下关于静态成员的说法错误的是"),
         {QStringLiteral("静态成员变量不属于某个特定对象"), QStringLiteral("对静态成员也可以指定为 private 或 public"), QStringLiteral("若某类没有对象存在，该类的静态成员变量就不存在"), QStringLiteral("在静态成员函数中，不能访问非静态成员变量，也不能调用非静态成员函数")},
         2,
         QStringLiteral("静态成员变量在程序开始时存在，不依赖对象。")},
        {QStringLiteral("以下容器中，元素的插入位置与元素的值有关的是"),
         {QStringLiteral("vector"), QStringLiteral("list"), QStringLiteral("map"), QStringLiteral("deque")},
         2,
         QStringLiteral("map根据键值排序插入。")},
        {QStringLiteral("在构造某一个封闭派生类的对象时，关于基类、成员对象类和派生类的构造函数执行顺序，以下说法正确的是"),
         {QStringLiteral("依次是基类、成员对象类、派生类"), QStringLiteral("依次是成员对象类、基类、派生类"), QStringLiteral("依次是派生类、基类、成员对象类"), QStringLiteral("跟初始化列表的顺序有关")},
         0,
         QStringLiteral("先基类，再成员对象，最后派生类自身。")},
        {QStringLiteral("下列关于运算符重载说法中错误的是："),
         {QStringLiteral("重载运算符() 和 [] 时，运算符重载函数必须声明为类的成员函数"), QStringLiteral("\"::\"、\".\"、\"sizeof\"均不能被重载"), QStringLiteral("C++不允许用户自己定义新的运算符,只能对已经存在的操作符进行重载"), QStringLiteral("\"=\" 可以重载为成员函数，也可以重载为非成员函数")},
         3,
         QStringLiteral("赋值运算符必须重载为成员函数。")},

        // 2019年
        {QStringLiteral("关于 vector 和 deque，以下说法正确的是："),
         {QStringLiteral("声明 vector a;之后，可以使用 a[10]=20;对 vector 中的元素赋值"), QStringLiteral("deque 不支持通过下标[]取值"), QStringLiteral("vector 和 deque 均可用 push()和 pop()增删元素"), QStringLiteral("对于 deque，可以通过 back()=x 的方式修改元素的值")},
         3,
         QStringLiteral("deque的back()返回引用，可以赋值。")},
        {QStringLiteral("关于 STL 算法，以下说法正确的是："),
         {QStringLiteral("max_element 算法要求 STL 容器已经排好序"), QStringLiteral("除了算法 sort 以外，vector 和 list 等容器均定义了自己的 sort 函数"), QStringLiteral("可作用于 set 的 for_each 算法不能改变容器中元素的值"), QStringLiteral("find 算法找不到对应的值，会返回 NULL")},
         2,
         QStringLiteral("for_each对set中的元素是只读的。")},
        {QStringLiteral("关于友元，以下说法正确的是："),
         {QStringLiteral("为了让 int func()函数访问 class A 的私有变量，可以在 class A 中声明 friend int func();"), QStringLiteral("如果 class A 是 class B 的友元类，则 A 的子类可以访问 B 类的私有变量。"), QStringLiteral("友元类的关系是相互的，如果 class A 是 class B 的友元类，则 A 可以访问 B 的私有变量，B 也可以访问 A 的私有变量。"), QStringLiteral("有两个名称、参数表、返回类型均相同的函数，其中一个函数是类 A 的友元而另一个不是，则这是一种函数重载")},
         0,
         QStringLiteral("友元声明正确。")},
        {QStringLiteral("派生类的成员函数，可以访问以下哪几种成员变量？ (1) 当前基类对象的 private 变量 (2) 当前基类对象的 protected 变量 (3) 其他基类对象的 protected 变量 (4) 其他同类对象的 private 变量"),
         {QStringLiteral("1, 2, 3."), QStringLiteral("1, 2"), QStringLiteral("2, 4"), QStringLiteral("2")},
         2,
         QStringLiteral("可访问自己基类部分的protected和同类对象的private。")},
        {QStringLiteral("关于抽象类，以下说法正确的是"),
         {QStringLiteral("抽象类的子类可能依然是抽象类"), QStringLiteral("无法定义一个抽象类的指针"), QStringLiteral("抽象类不能包含非虚函数"), QStringLiteral("无法定义抽象类的构造函数")},
         0,
         QStringLiteral("子类若不实现纯虚函数，则仍是抽象类。")},
        {QStringLiteral("基类和派生类定义了同名的函数 int func()，那么"),
         {QStringLiteral("派生类的对象无法调用基类的 func 函数"), QStringLiteral("如果基类的 func 函数是 virtual 函数，则基类是抽象类，无法被直接构造。"), QStringLiteral("如果基类的 func 函数是 virtual 函数，此时如果一个基类指针指向了一个派生类的对象，那么它在调用 func()时，会调用派生类的 func()函数。"), QStringLiteral("如果派生类的 func 函数是 virtual 函数，基类的不是，此时如果一个基类指针指向了一个派生类的对象，那么它在调用 func()时，会调用派生类的 func()函数。")},
         2,
         QStringLiteral("基类指针调用虚函数，动态绑定到派生类。")},
        {QStringLiteral("以下关于构造函数和析构函数描述错误的是："),
         {QStringLiteral("构造函数可以重载，析构函数不能重载"), QStringLiteral("析构函数可以带或不带参数"), QStringLiteral("类的构造函数和析构函数不能被它的派生类继承。"), QStringLiteral("类中如果没有定义复制构造函数，则编译器将自动生成一个默认的")},
         1,
         QStringLiteral("析构函数不能有参数。")},
        {QStringLiteral("下面对静态数据成员的描述，正确的是："),
         {QStringLiteral("对于一个类的某个静态数据成员，该类的不同对象可以有不同的值"), QStringLiteral("静态数据成员不能通过类的对象调用"), QStringLiteral("静态数据成员可以通过初始化列表来初始化"), QStringLiteral("静态数据成员可以定义为 private")},
         3,
         QStringLiteral("静态成员可以私有。")},
        {QStringLiteral("类 TM 和 类 TN 是两个独立的类，那么类 TM 中哪种形式的成员变量一定是不允许的"),
         {QStringLiteral("TM *a;"), QStringLiteral("TM &a;"), QStringLiteral("TM a;"), QStringLiteral("TN a;")},
         2,
         QStringLiteral("类中不能包含自身类型的非静态成员，会导致无限递归。")},
        {QStringLiteral("下列情况中，不会调用拷贝构造函数的是"),
         {QStringLiteral("用一个对象去初始化同一类的另一个新对象时"), QStringLiteral("将类的一个对象赋值给该类的另一个对象时"), QStringLiteral("函数的形参是类的对象，调用函数进行形参和实参结合时"), QStringLiteral("函数的返回值是类的对象，函数执行返回调用时")},
         1,
         QStringLiteral("赋值操作调用赋值运算符。")},
        {QStringLiteral("下列哪个运算符可以被重载"),
         {QStringLiteral("->"), QStringLiteral("."), QStringLiteral("?:"), QStringLiteral("sizeof")},
         0,
         QStringLiteral("->可以重载。")},
        {QStringLiteral("下列关于 STL 的说法错误的是"),
         {QStringLiteral("vector 支持随机访问，在尾部增删有比较好的性能。"), QStringLiteral("list 在内存上是不连续的，不支持随机访问，在两端增删有比较好的性能。"), QStringLiteral("deque 支持随机访问，在两端增删元素有比较好的性能。"), QStringLiteral("std::copy 函数可以作用于 vector、list、deque 和 priority_queue。")},
         3,
         QStringLiteral("priority_queue没有迭代器，不能用copy。")},
        {QStringLiteral("以下 STL 中的函数模板哪个可以作用于 set"),
         {QStringLiteral("find"), QStringLiteral("random_shuffle"), QStringLiteral("sort"), QStringLiteral("都不行")},
         0,
         QStringLiteral("find算法可用于set。")},
        {QStringLiteral("关于构造函数，错误的说法是"),
         {QStringLiteral("构造函数中不可以访问类的纯 virtual 函数"), QStringLiteral("每个类都有无参数的构造函数"), QStringLiteral("构造函数可以是类的 private 成员"), QStringLiteral("每个类都有复制构造函数")},
         1,
         QStringLiteral("如果用户定义了构造函数，则没有默认无参构造。")},
        {QStringLiteral("关于多态，下列说法错误的是；"),
         {QStringLiteral("通过派生类指针访问了基类成员变量，不一定是多态"), QStringLiteral("通过派生类引用访问了基类成员函数，不一定是多态"), QStringLiteral("通过\"基类指针->函数名()\"不能调用派生类的私有虚函数"), QStringLiteral("在类的构造函数中调用虚函数，不可能是多态")},
         2,
         QStringLiteral("基类指针可以调用派生类的私有虚函数，只要基类接口是公有的。")},
        {QStringLiteral("类模板 T 实例化为两个模板类 A 和 B，则"),
         {QStringLiteral("A 的友元函数可能也是 B 的友元函数"), QStringLiteral("A 的静态成员变量和 B 的静态成员变量可能在程序中位于同一地址"), QStringLiteral("可以把 A 的对象赋值给 B 的对象"), QStringLiteral("A 的成员函数中，可以访问 B 的私有成员")},
         0,
         QStringLiteral("模板实例化后是不同的类，但友元关系可能通过模板参数传递。")},
        {QStringLiteral("在程序中，希望定义输出文件流 ofstream 来完成以二进制格式输出到文件 output.txt 尾部，保留 output.txt 的现有数据的工作。应当采用的最正确的打开文件的方式是："),
         {QStringLiteral("ofstream outFile(\"output.txt\",ios::out);"), QStringLiteral("ofstream outFile(\"output.txt\",ios::app);"), QStringLiteral("ofstream outFile(\"output.txt\",ios::out|ios::binary);"), QStringLiteral("ofstream outFile(\"output.txt\",ios::app|ios::binary);")},
         3,
         QStringLiteral("app模式追加，binary二进制。")},
        {QStringLiteral("以下关于 C++语言中虚函数的描述错误的是："),
         {QStringLiteral("构造函数不可以是虚函数"), QStringLiteral("析构函数不可以是纯虚函数"), QStringLiteral("构造函数中不应该调用纯虚函数"), QStringLiteral("struct 中不可以定义虚函数")},
         3,
         QStringLiteral("struct中也可以定义虚函数。")},
        {QStringLiteral("下列说法错误的是"),
         {QStringLiteral("静态成员函数可以为虚函数"), QStringLiteral("每个类可以有多个构造函数但只有一个析构函数"), QStringLiteral("多态的函数调用语句中，函数一定是虚函数"), QStringLiteral("通过\"基类指针->成员函数名\"的方式调用成员函数，不一定是多态")},
         0,
         QStringLiteral("静态成员函数不能是虚函数。")},
        {QStringLiteral("有模板如下： template <class T> int func(T op,int n) { return op(n); } 以下 4 项中有几项不可能成为调用 func 模板时的第一个实参？ 1) int 类型的变量 2) 对象 3) 函数名 4) 函数指针"),
         {QStringLiteral("0"), QStringLiteral("1"), QStringLiteral("2"), QStringLiteral("3")},
         1,
         QStringLiteral("int类型变量不能作为函数对象调用，其他可以。")},

        // 2021年
        {QStringLiteral("下列说法错误的是："),
         {QStringLiteral("对于内联函数，编译器会将整个函数的代码插入到调用语句处 , 而不会生出调用函数的语句。"), QStringLiteral("如果静态成员变量是 public 的，那么在没有对象生成的时候也能直接访问。"), QStringLiteral("常量对象只能使用构造函数, 析构函数和有 const 说明的函数（常量方法）。"), QStringLiteral("所有成员函数中都可以用 this 来代表指向该函数作用的对象的指针。")},
         3,
         QStringLiteral("静态成员函数中没有this指针。")},
        {QStringLiteral("下面哪个选项是错误的："),
         {QStringLiteral("运算符重载不改变运算符的优先级"), QStringLiteral("以下运算符不能被重载:sizeof, ->, ::"), QStringLiteral("赋值运算符 = 只能重载为类的成员函数"), QStringLiteral("后置++和--运算符作为二元运算符重载，前置++和--运算符作为一元运算符重载")},
         1,
         QStringLiteral("->运算符可以被重载。")},
        {QStringLiteral("下面的说法中正确的是："),
         {QStringLiteral("可以用迭代器指向 priority_queue 中的元素"), QStringLiteral("可以用 sort 算法对 list 进行排序"), QStringLiteral("deque 支持用 [i] 来访问第 i 个元素的引用"), QStringLiteral("vector, deque, list 都是顺序容器，迭代器类型都是随机访问迭代器")},
         2,
         QStringLiteral("deque支持下标操作。")},
        {QStringLiteral("下列说法错误的是："),
         {QStringLiteral("右值引用能够避免不需要的深拷贝。"), QStringLiteral("智能指针 shared_ptr 对象需要使用 reset 方法托管指向动态分配的数组的指针。"), QStringLiteral("无序容器的优势是查询和插入的速度快，但是无法按照键值大小顺序访问。"), QStringLiteral("Lambda 表达式中如果没有用->指定返回值类型，则编译器自动判断返回值类型。")},
         1,
         QStringLiteral("shared_ptr管理数组需指定删除器，reset不能直接托管数组。")},
        {QStringLiteral("类 C1 和类 C2 都是类模板 CT 的模板类，下列说法正确的是："),
         {QStringLiteral("C1 的成员函数可以访问 C2 的私有成员"), QStringLiteral("C1 对象和 C2 对象的大小是相同的"), QStringLiteral("C1 的静态成员变量和 C2 的静态成员变量拥有不同的存储空间"), QStringLiteral("C1 的对象，可以赋值给 C2 类型的变量")},
         2,
         QStringLiteral("不同模板实例的静态成员独立。")},
        {QStringLiteral("关于 C++中的多态，下列说法正确的是："),
         {QStringLiteral("类 B 是类 A 的子类，则若类 A 指针 p 指向一个类 B 的对象，则通过 p 可以调用在 B 中有定义而 A 中没有定义的成员函数"), QStringLiteral("在类中是否存在虚函数不影响它的对象所占用的空间大小。"), QStringLiteral("多态必须通过用基类指针调用基类中的虚函数的方式来实现"), QStringLiteral("类 B 是类 A 的子类，并且只在 A 中定义了虚析构函数，则类 B 和类 A 都会有虚函数表")},
         3,
         QStringLiteral("有虚函数就会有虚表，派生类继承虚表。")},
        {QStringLiteral("以下的运算符中哪个不能重载"),
         {QStringLiteral("?:"), QStringLiteral("++"), QStringLiteral("<<="), QStringLiteral("==")},
         0,
         QStringLiteral("条件运算符不能重载。")},
        {QStringLiteral("下⾯哪个操作可以将 bitset<114> x; 设置为全 0 bitset?"),
         {QStringLiteral("x.clear();"), QStringLiteral("x.reset();"), QStringLiteral("x.flip();"), QStringLiteral("x.none();")},
         1,
         QStringLiteral("reset()将全部位设为0。")},
        {QStringLiteral("下⾯说法正确的是"),
         {QStringLiteral("流操作算子也同样适用于文件流"), QStringLiteral("fstream 只能从⽂件读取数据，不能向⽂件写⼊数据。"), QStringLiteral("iostream 类可以用于读写文件。"), QStringLiteral("istream 是⽤于输出的流类。")},
         0,
         QStringLiteral("流操作符如<< >>也适用于文件流。")},
        {QStringLiteral("下列四句话中正确的有___个。"),
         {QStringLiteral("0"), QStringLiteral("1"), QStringLiteral("2"), QStringLiteral("3")},
         2,
         QStringLiteral("原题缺具体四句话，根据文档答案选C（2个）。")},
        {QStringLiteral("关于 virtual 修饰符, 下⾯说法正确的是:"),
         {QStringLiteral("使⽤ virtual 修饰符修饰成员函数，不会导致类的对象需要更⼤的内存空间"), QStringLiteral("静态成员函数也可以用 virtual 修饰"), QStringLiteral("如果基类的析构函数不是 virtual 的, 则 delete 一个指向派生类对象的基类指针，不会执行派生类的析构函数"), QStringLiteral("没有用 virtual 修饰的成员函数，一定不是虚函数")},
         2,
         QStringLiteral("基类析构非虚，派生类析构不会调用。")},
        {QStringLiteral("关于静态成员函数，哪些说法是对的？ 1）它可以访问非静态成员 2）它可以访问其他静态成员函数 3）它可以访问全局数据和函数 4）它可以访问 this 指针"),
         {QStringLiteral("全都对"), QStringLiteral("只有 2"), QStringLiteral("只有 2, 3, 4"), QStringLiteral("只有 2, 3")},
         3,
         QStringLiteral("静态成员函数只能访问静态成员和全局数据。")},
        {QStringLiteral("在以下哪种情形，复制构造函数会被调用?"),
         {QStringLiteral("当一个对象采用引用方式，作为参数传递给一个函数"), QStringLiteral("当一个函数返回一个对象"), QStringLiteral("当一个对象赋值给另一个对象"), QStringLiteral("以上答案都不对")},
         1,
         QStringLiteral("函数返回对象时调用拷贝构造。")},
        {QStringLiteral("关于析构函数说法正确的是："),
         {QStringLiteral("无形参，也不可重载"), QStringLiteral("其名与类名完全相同"), QStringLiteral("函数体中必须有 delete 语句"), QStringLiteral("返回类型是 void")},
         0,
         QStringLiteral("析构函数无形参、不可重载。")},
        {QStringLiteral("以下正确的是："),
         {QStringLiteral("运算符只能重载为成员函数或友元函数"), QStringLiteral("cout<<a 里面的<<运算符可以重载为 a 的成员函数"), QStringLiteral("一个函数可以同时作为多个类的友元函数"), QStringLiteral("一个类的友元函数可以同时是这个类的虚函数")},
         2,
         QStringLiteral("一个函数可以是多个类的友元。")},
        {QStringLiteral("以下支持[]运算符的类模板共多少个？ vector,deque,list,set,multiset,map,multimap,stack,queue,priority_queue"),
         {QStringLiteral("3"), QStringLiteral("4"), QStringLiteral("5"), QStringLiteral("6")},
         0,
         QStringLiteral("vector,deque,map支持[]，共3个。")},
        {QStringLiteral("以下函数或类使用时一定不会出现二义性的有："),
         {QStringLiteral("void x(int y); void x(int p, int q=0);"), QStringLiteral("class x{public: int p;}; class y{public:int p;}; class z: public x, public y{};"), QStringLiteral("template<class Foo> int print(Foo x); template<class Bar> void print(Bar y);"), QStringLiteral("template<class Foo> int print(Foo x); void print(int y);")},
         3,
         QStringLiteral("函数模板与普通函数重载，调用时普通函数优先，无二义性。")},
        {QStringLiteral("class Foo1 {public int x;}; class Foo2 {static int x;}; class Foo3 {const int x;}; class Foo5 {virtual int x;}; 其中错误的定义有多少条："),
         {QStringLiteral("0"), QStringLiteral("1"), QStringLiteral("2"), QStringLiteral("3")},
         2,
         QStringLiteral("Foo1缺少访问限定符后面的冒号，Foo3 const成员未初始化，共2处错误。")},
        {QStringLiteral("以下语法正确的是："),
         {QStringLiteral("void foo(int a=0, int b){}"), QStringLiteral("int arr[]{1,2,3};"), QStringLiteral("int & r = 2+3;"), QStringLiteral("template < class T1, T2>")},
         1,
         QStringLiteral("C++11允许int arr[]{1,2,3}。")},
        {QStringLiteral("以下正确的是："),
         {QStringLiteral("一个最小值优先的优先队列类型定义为 priority_queue < int, greater <int> >"), QStringLiteral("end()返回指向容器中最后一个元素的迭代器"), QStringLiteral("在 vector 里面插入新元素一定是常数时间"), QStringLiteral("unique 算法不会修改 vector 的大小")},
         3,
         QStringLiteral("unique只是将重复元素移到末尾，不改变大小，需要配合erase。")}
    };
}
